name: french_example

dependencies:
  glob: ">=1.1.7 <2.0.0"
  path: ">=1.6.2 <2.0.0"
  test: ">=1.6.1 <2.0.0"
  matcher: ">=0.12.5 <1.0.0"

dev_dependencies:
  pedantic: ">=1.5.0 <2.0.0"

  gherkin:
    git:
      url: https://github.com/jonsamwell/dart_gherkin.git
      ref: f0b3f955191b53a78075ed2c9387ea8bee12f111

environment:
  sdk: ">=2.6.0 <3.0.0"
